spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxx.xxx.xxx:3306/xxx?useSSL=false&useUnicode=true&characterEncoding=UTF8&autoReconnect=true
    username: xxx
    password: xxx
